# Generated by Django 4.1 on 2022-08-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_headshot_book_release_day_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='headshot',
            new_name='image_of_book',
        ),
    ]
