# Generated by Django 4.1 on 2022-08-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_image_of_book_book_cover_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrow_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
