# Generated by Django 4.1 on 2022-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_book_genre_alter_book_isbn_alter_book_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrow',
            field=models.CharField(blank=True, choices=[('w', 'waiting'), ('d', 'denied'), ('e', 'aproved')], default='m', help_text='Book borrow', max_length=1),
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
